# Generated by Django 5.0.1 on 2024-02-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, default='', max_length=20)),
                ('LastName', models.CharField(blank=True, default='', max_length=20)),
                ('Email', models.CharField(blank=True, default='', max_length=50)),
                ('Username', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
