# Generated by Django 5.0.2 on 2024-02-22 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityclasses',
            options={'verbose_name_plural': 'University Class'},
        ),
    ]
